### PR TITLE
Made changes to Action (config is not refering to R versions)

### PR DESCRIPTION
**Pull request by MowahidLatif**
Thank you for taking the time to submit a pull request!

To maximize the chances of acceptance:

* The title of your PR should briefly describe the change.

* The body of your PR should contain `Fixes #issue-number` (if relevant).

* Commit/merge messages to be included in NEWS.md should begin with `-`.

* Code should follow the tidyverse [style guide](https://style.tidyverse.org).

* Documentation should use roxygen2, with Markdown syntax.

* Contributions should include unit tests (using `testthat`).

For more information see [Contributing](/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by aylapear** [comment]
The reason the devel is failing is suspicious... because its the Dev version and passing in all other version there is a possibility it is because the dev version just has a weirdness in it now. We should wait to accept this pull request and try retrigger the action in a couple days to see if anything has changed.

**Comment by MowahidLatif** [comment]
Ok, how long should we wait? I can try this again is that'll make a difference.

**Comment by aylapear** [comment]
I posted a question in the GitHub support community to see if they had anything to say about this. I have see this issue before and I don't understand what could be causing it. I think its just a bug. It could be fixed tomorrow or in a month or never. As the others get accepted and this one is still left we can make a call then.

**Comment by MowahidLatif** [comment]
Ok, that makes sense. I will skip this for now.

**Pull request merged**
